workspace:
  base: /go
  path: src/github.com/${DRONE_REPO_OWNER}/${DRONE_REPO_NAME}

pipeline:
  deps:
    image: golang:1.10
    pull: true
    commands:
    - go get -u github.com/golang/dep/cmd/dep
    - dep ensure

  test:
    image: golang:1.10
    commands:
    - go vet
    - go test ./... -cover -coverprofile=coverage.out

  build_linux_amd64:
    image: golang:1.10
    group: build
    environment:
    - GOOS=linux
    - GOARCH=amd64
    - CGO_ENABLED=0
    commands:
    - |
      if test "${DRONE_TAG}" = ""; then
        go build -v -ldflags "-X main.build=${DRONE_BUILD_NUMBER}" -a -o release/linux/amd64/${DRONE_REPO_NAME}
      else
        go build -v -ldflags "-X main.version=${DRONE_TAG##v} -X main.build=${DRONE_BUILD_NUMBER}" -a -o release/linux/amd64/${DRONE_REPO_NAME}
      fi

  publish_linux_amd64:
    image: plugins/docker
    repo: claimcompass/drone-helm
    secrets: [ docker_username, docker_password ]
    auto_tag: true
    when:
      event: [ tag, push ]
      branch: [ master ]
